/*insert into Course (courseID, courseName, instructor, time, creditHours) values ('XWD918-M006', 'Algebra', 'Cirstoforo Algar', '2:58:15', 2);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('UKT869-M001', 'Fashion', 'Margot Killingbeck', '3:12:22', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('VWN234-M000', 'Anatomy and Physiology', 'Esme Gunton', '16:19:28', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('WND490-M007', 'Technical Communications', 'Pattie Kemble', '6:28:48', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('PAE690-M009', 'History', 'Starlin Rosander', '23:46:06', 2);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('MBW263-M006', 'Algebra', 'Alix Allawy', '16:33:24', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('HOL762-M009', 'Differential Equations', 'Magdalen Gregoire', '7:19:11', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('IJA930-M006', 'Technical Communications', 'Dayna Kornilov', '15:12:17', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('BCT783-M007', 'Differential Equations', 'Nobe Bottjer', '14:56:42', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('WIE252-M003', 'Aeronautical Engineering', 'Clerc Girardeau', '10:37:27', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('YAD307-M007', 'Physics', 'Birk Harvison', '19:42:04', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('NGD319-M002', 'Differential Equations', 'Florie Ragbourn', '21:53:39', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('ZDP973-M006', 'Physics', 'Brnaby Tethacot', '7:31:07', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('PST363-M005', 'Chemistry', 'Weylin Bruckenthal', '1:23:30', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('DIC447-M001', 'Anatomy and Physiology', 'Jordan Dornin', '9:53:33', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('JMR289-M009', 'Physics', 'Alberik Seeviour', '6:48:57', 2);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('NAF073-M008', 'Physics', 'Wynny Enrigo', '18:19:11', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('CEV243-M006', 'Aeronautical Engineering', 'Cliff Courtier', '12:13:15', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('RCX252-M006', 'German', 'Samuele Wimmer', '12:15:45', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('LGF792-M009', 'English', 'Adara Khomich', '18:54:57', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('AXL509-M008', 'Archeology', 'Arni Grahl', '10:03:05', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('MIS718-M001', 'History', 'Jephthah Austwick', '23:52:39', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('YON649-M009', 'German', 'Imogene Bidwell', '19:21:05', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('USU882-M007', 'Technical Communications', 'Sybilla Jenny', '22:43:29', 2);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('NJM619-M000', 'German', 'Charlotta Clappison', '8:07:29', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('OZU406-M008', 'History', 'Zilvia Morrish', '4:35:36', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('LDZ843-M006', 'Fashion', 'Jada Dielhenn', '10:55:01', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('FEP249-M006', 'History', 'Reginauld Bernardos', '1:15:36', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('NHX880-M001', 'Archeology', 'Tully Durno', '10:19:15', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('EOY427-M002', 'Computer Science', 'Agnesse Sikorsky', '15:58:39', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('OTM969-M004', 'Computer Science', 'Brittani Duffield', '14:33:09', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('HCT817-M009', 'Differential Equations', 'Malina Dimbleby', '3:28:05', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('NUX953-M004', 'Psychology', 'Rozalin Szymanek', '10:12:39', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('DQH424-M009', 'Technical Communications', 'Iolande Brasse', '6:19:48', 2);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('HPT200-M001', 'Computer Science', 'Cesya Byles', '15:55:58', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('RIO031-M009', 'Math', 'Gaye Chaffey', '15:36:53', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('EMF914-M002', 'Differential Equations', 'Riannon Brickham', '14:27:07', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('UKG044-M005', 'Archeology', 'Prudi Spitell', '4:39:21', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('DIY082-M006', 'German', 'Persis Ghelardi', '13:12:43', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('JEG324-M005', 'Archeology', 'Lorettalorna Trasler', '13:45:44', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('CIA668-M005', 'English', 'Celestia Domingues', '16:47:53', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('IER745-M003', 'Math', 'Stinky Zeale', '22:41:05', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('LVU425-M006', 'French', 'Holly-anne Gossart', '10:43:54', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('OSC575-M006', 'History', 'Zia Awin', '13:35:29', 1);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('PNH924-M004', 'English', 'Lynea Burrells', '21:38:40', 2);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('QKV042-M002', 'French', 'Tyson Daish', '7:35:33', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('QWP136-M005', 'Computer Science', 'Oliviero Beaver', '23:10:51', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('GIY030-M005', 'Algebra', 'Starlene Thomassen', '22:55:28', 4);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('PML096-M001', 'Spanish', 'Kippar Hardingham', '8:48:44', 2);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('KKL273-M005', 'Aeronautical Engineering', 'Munmro Robe', '17:46:19', 3);

insert into Course (courseID, courseName, instructor, time, creditHours) values ('CSC484-M001', 'Database Management', 'Mengyu Qiao', '10:00:00', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('CSC426-M001', 'Cybersecurity', 'Mengyu Qiao', '14:00:00', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('MAT415-M001', 'Abstract Algebra', 'Patrick Fleming', '8:00:00', 3);*/
insert into Course (courseID, courseName, instructor, time, creditHours) values ('CSC468-M001', 'Graphical User Interface Programming', 'Lisa Rebenitsch', '11:00:00', 3);
insert into Course (courseID, courseName, instructor, time, creditHours) values ('CSC449-M001', 'Natural Computing', 'Jeff McGough', '13:00:00', 3);
